---
- include_vars: "vars/{{env}}.yml"

- name: Nginx | Install Nginx
  apt:
    pkg=nginx
    state=latest

- name: Nginx | Remove default vhost
  file: dest=/etc/nginx/sites-available/default state=absent
- name: Nginx | Remove default vhost enabled symlink
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Nginx | Ensure Nginx is running
  service: name=nginx state=started

- name: Nginx | Check that path /var/www exists
  file: dest=/var/www state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

- name: Nginx | Check vhost path exists
  file: dest=/etc/nginx/sites-available state=directory owner=root group=root mode=0700

- name: Nginx | Copy host file
  template: src="templates/{{ env }}.j2" dest=/etc/nginx/sites-available/default.conf mode=0700
  notify: nginx-restart

- name: Nginx | Create host symlink
  file: path=/etc/nginx/sites-enabled/default.conf state=link src=/etc/nginx/sites-available/default.conf
  notify: nginx-restart
